version: "3"

volumes:
  postgres_data: {}
  static-content: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: grid_points
    container_name: grid_points_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
      - static-content:/static
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:13.2
    container_name: grid_points_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"
